services:
  postgres:
    restart: "no"
    image: postgres:14-alpine
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 1s
      timeout: 5s
      retries: 6
    ports:
      - "5432:5432"
    volumes:
      - ./pg-init-scripts:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_MULTIPLE_DATABASES=todo
    networks:
      - quarkus
  quarkus-maven-kotlin:
    depends_on:
      postgres:
        condition: service_healthy
    build:
      context: ../../../..
      dockerfile: src/main/docker/Dockerfile.native-micro
      tags:
        - quarkus/quarkus-maven-kotlin
    restart: "no"
    image: quarkus/quarkus-maven-kotlin
    ports:
      - "8080:8080"
    environment:
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://postgres:5432/todo
      - QUARKUS_DATASOURCE_USERNAME=postgres
      - QUARKUS_DATASOURCE_PASSWORD=postgres
    networks:
      - quarkus
networks:
  quarkus:
    driver: bridge
